config/routes.rb
Apps::Application.routes.draw do
  get "sessions/new"

  get "users/new"
  get "log_in" => "sessions#new", :as => "log_in" 
  resources :sessions 

  resources :articles
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "articles#index"
  resources :users
  get "log_out" => "sessions#destroy", :as => "log_out"
  match 'articles/:id', :to => 'articles#show', :as => "show_article" 

  match ':controller(/:action(/:id(.:format)))'
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title, :user_id
  
  validates :title, :presence => true,
                    :uniqueness => true,
                    :length => {:minimum => 1,:maximum => 100}

  has_many :comment, :dependent => :destroy
  belongs_to :user
  scope :rating_is_and_above, lambda {|rating| where("rating > ?", rating)}
end

app/models/categories_product.rb
class CategoriesProduct < ActiveRecord::Base
  belongs_to :category
  belongs_to :product
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, :through => :categories_products
  has_many :categories_products
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :users, :dependent => :destroy
  validate :name, :presence => true,
                  :length => {:minimum => 1, :maximum => 15}
  validate :valid_code
  def valid_code
    self.errors[:code] << "Only can be filled with id/usa/frc" if (code != "id" && code != "usa" && code!= "frc")
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :user
  has_many :categories, :through => :categories_products
  has_many :categories_products
  scope :price_more_than_1000, where("price > 1000")
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
#  validates :first_name, :presence => true,
#                         :length => {:minimum => 1, :maximum => 20},
#                         :format => {:with => /[a-zA-Z\s]+$/}
#  validates :last_name, :presence => true,
#                        :length => {:minimum => 1, :maximum => 20},
#                        :format => {:with => /[a-zA-Z\s]+$/}
  validates :password, :presence => {:on => :create},
                       :confirmation => true
  validates :email, :presence => true,
                    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i},
                    :uniqueness => true
#  validates :username, :presence => true,
#                      :format => {:with => /[a-z0-9\s]+$/},
#                      :uniqueness => true
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  has_many :products, :dependent => :destroy
  has_many :articles, :dependent => :destroy
  belongs_to :country
  has_many :shared_articles, :class_name => "Article", 
                             :foreign_key => "user_id",
                             :conditions => "title like '%share%'"

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  def require_login
    if current_user.nil?
      flash[:error] = "You are not permitted, please login first"
      redirect_to log_in_path
    else
      return current_user
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :edit, :update, :destroy]
  
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new  
  end

  def create
    @article= Article.new(params[:article])
    if @article.save
      flash[:notice] = "Article successfully saved"
      redirect_to :action => :index
    else
      flash.now[:notice] = "Article failed to saved"
      render :action => :new
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to articles_path, :notice => 'Article was successfully updated.'
    else
      flash[:error] = 'Article was failed to update.'
      render :action => 'edit'
    end
  end

  def index
    @articles = Article.all
  end

  def destroy
    Article.destroy(params[:id])
    redirect_to articles_path, :notice => 'Article was successfully deleted'
  end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end

  def say_hello
    render :text => "<h1>Hello World</h1>"
  end
  
  def say
    @hello = "Hello World"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to articles_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password" 
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/test_controller.rb
class TestController < ApplicationController


  def index
  end

  def say_hello
    render :text => "<h1>Hello World</h1>"
  end
  
  def say
    @hello = "Hello World"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if verify_recaptcha
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        redirect_to root_url, :notice => "Signed up!"
      else
        render "new"
      end
      else
    flash[:error] = "There was an error with the recaptcha code below.
                     Please re-enter the code and click submit."
    render "new"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
def welcome_text
  str = "" #jika user telah login, tampilkan welcome textnya
  if current_user
    str = "Welcome, #{current_user.email} | "
    str += link_to "Logout", log_out_path
  else
    str = "#{link_to "Login", log_in_path} | "
    str += link_to "Signup", sign_up_path
  end
end 
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<table>
<%= form_for @article do |article| %>
  <tr>
    <td><%= article.label :title %></td>
    <td><%= article.text_field :title %></td>
  </tr>
  <tr>
    <td><%= article.label :body %></td>
    <td><%= article.text_area :body %></td>
  </tr>
  <tr>
    <td><%= article.submit %></td>
  </tr>
<% end %>
</table>

app/views/articles/index.html.erb
<h1>List Of Articles</h1>
<%= flash[:notice] %>
<table class=list_articles>
  <tr>
    <td>Title</td>
    <td>Content</td>
    <td>Option</td>
  </tr>
  <% @articles.each do |article|%>
  <tr>
  <td><%= article.title %></td>
  <td><%= article.body %></td>
  <td><%= link_to "Show", article, :class => "no-border" %> <%= link_to 'Edit', edit_article_path(article.id) %> <%= link_to 'Delete', article_path(article.id), :confirm => 'Are you sure want to delete this item?', :method => :delete %>
  </tr>
  <% end %>
</table>
<p><%= link_to "Add new Article", new_article_path%></p>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= flash[:notice] %>
<table>
<%= form_for @article do |article| %>
  <tr>
    <td><%= article.label :title %></td>
    <td><%= article.text_field :title %></td>
  </tr>
  <tr>
    <td><%= article.label :body %></td>
    <td><%= article.text_area :body %></td>
  </tr>
  <tr>
    <td><%= article.submit %></td>
  </tr>
<% end %>
</table>

app/views/articles/show.html.erb
<div class="content">
  <h4>Article Detail</h4>
  <table class=list_articles>
    <tr>
      <td><strong>Title</strong> : </td>
      <td><%= @article.title %></td>
    </tr>
    <tr> 
      <td><strong>Content</strong> : </td>
      <td><%= @article.body %></td>
    </tr>
    <tr> 
      <td><strong>Created_at</strong> : </td>
      <td><%= @article.created_at %></td>
    </tr>
    <tr> 
      <td><strong>updated_at</strong> : </td>
      <td><%= @article.updated_at %></td>
    </tr>
  </table>
</div>
<%= link_to 'Back to Articles', articles_path %>

app/views/hello/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wgs</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<h1>Hello World</h1>

<h2><%= @hello %></h2>

</body>
</html>

app/views/hello/say.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wgs</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<h2><%= @hello %></h2>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articles</title>
  <%= stylesheet_link_tag    "application","style" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class=container>
    <%= raw(welcome_text) %>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1> 
 
<%= form_for @user do |f| %> 
  <% if @user.errors.any? %> 
    <div class="error_messages"> 
      <h2>Form is invalid</h2> 
      <ul> 
        <% for message in @user.errors.full_messages %> 
          <li><%= message %></li> 
        <% end %> 
      </ul> 
    </div> 
  <% end %> 
  <p> 
    <%= f.label :email %><br /> 
    <%= f.text_field :email %> 
  </p> 
  <p> 
    <%= f.label :password %><br /> 
    <%= f.password_field :password %> 
  </p> 
  <p> 
    <%= f.label :password_confirmation %> <br />
    <%= f.password_field :password_confirmation %> 
  </p> 
  <%= recaptcha_tags %>
  <p class="button"><%= f.submit %></p> 
<% end %> 